/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import Koneksi.koneksi;
import penjualan.Nota;

/**
 *
 * @author bayua
 */
public class popupbarang extends javax.swing.JFrame {
private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    
    public Nota brg = null;
    /**
     * Creates new form popupbarang
     */
    public popupbarang() {
        initComponents();
        setLocationRelativeTo(null);
         datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcarib = new javax.swing.JTextField();
        bcarib = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcarib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaribKeyPressed(evt);
            }
        });

        bcarib.setText("Cari");
        bcarib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaribActionPerformed(evt);
            }
        });

        tblbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcarib, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcarib)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcarib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcarib))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcaribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaribActionPerformed
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_bcaribActionPerformed

    private void tblbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangMouseClicked
      int tablePelanggan =
    tblbarang.getSelectedRow();

    brg.kdbrg =
    tblbarang.getValueAt(tablePelanggan,0)
    .toString();

    brg.nmbrg =
    tblbarang.getValueAt(tablePelanggan,1)
    .toString();

    brg.jenisbrg =
    tblbarang.getValueAt(tablePelanggan,2)
    .toString();

    brg.hb =
    tblbarang.getValueAt(tablePelanggan,3)
    .toString();

    brg.hj =
    tblbarang.getValueAt(tablePelanggan,4)
    .toString();

    brg.itemTerpilihbrg();

    this.dispose();
    }                                      

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {                                      
    datatable();
    }                                     

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {                                   
    if (evt.getKeyCode()
        == KeyEvent.VK_ENTER) {

        datatable();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbarangMouseClicked

    private void txtcaribKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaribKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaribKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popupbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcarib;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbarang;
    private javax.swing.JTextField txtcarib;
    // End of variables declaration//GEN-END:variables



protected void datatable() {

        Object[] Baris = {

            "Kode Barang",
            "Nama Barang",
            "Jenis",
            "Harga Beli",
            "Harga Jual"
        };

        tabmode =
        new DefaultTableModel(null, Baris);

        String cariitem =
        txtcarib.getText();

        try {

           
            String sql =
            "SELECT * FROM barang "
            + "WHERE id_barang LIKE '%" + cariitem + "%' "
            + "OR nama_barang LIKE '%" + cariitem + "%'";

            Statement stat =
            conn.createStatement();

            ResultSet hasil =
            stat.executeQuery(sql);

            while (hasil.next()) {

                tabmode.addRow(
                new Object[] {

                    hasil.getString("id_barang"),
                    hasil.getString("nama_barang"),
                    hasil.getString("jenis"),
                    hasil.getString("harga_beli"),
                    hasil.getString("harga_jual")
                });
            }

            tblbarang.setModel(tabmode);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
            null,
            "Data gagal dipanggil : "
            + e.getMessage()
            );
        }
}
}