/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import Koneksi.koneksi;
import penjualan.Nota;
/**
 *
 * @author bayua
 */
public class popuppelanggan extends javax.swing.JFrame {
private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    
    public Nota plgn = null;
    /**
     * Creates new form popuppelanggan
     */
    public popuppelanggan() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcarip = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcarip.setForeground(new java.awt.Color(204, 204, 204));
        txtcarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaripActionPerformed(evt);
            }
        });
        txtcarip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaripKeyPressed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblplgn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcarip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcarip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
       try {

            int row =
            tblplgn.getSelectedRow();

            plgn.id =
            tblplgn.getValueAt(row,0).toString();

            plgn.nama =
            tblplgn.getValueAt(row,1).toString();

            plgn.jenis =
            tblplgn.getValueAt(row,2).toString();

            plgn.telp =
            tblplgn.getValueAt(row,3).toString();

            plgn.alamat =
            tblplgn.getValueAt(row,4).toString();

            plgn.itemterpilih();

            this.dispose();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
            null,
            "Gagal pilih data : "
            + e.getMessage()
            );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseClicked

    private void txtcaripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaripKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaripKeyPressed

    private void txtcaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaripActionPerformed
         //if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            //datatable();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popuppelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popuppelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popuppelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popuppelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popuppelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextField txtcarip;
    // End of variables declaration//GEN-END:variables



    protected void datatable() {
   Object[] Baris = {

            "ID Pelanggan",
            "Nama",
            "Jenis Kelamin",
            "No Telepon",
            "Alamat"
        };

        tabmode =
        new DefaultTableModel(null, Baris);

        String cariitem =
        txtcarip.getText();

        try {

            String sql =
            "SELECT * FROM pelanggan "
            + "WHERE id LIKE '%" + cariitem + "%' "+ "OR namaplg LIKE '%" + cariitem + "%'";

            Statement stat =
            conn.createStatement();

            ResultSet hasil =
            stat.executeQuery(sql);

            while (hasil.next()) {

                tabmode.addRow(
                new Object[] {

                    hasil.getString("id"),
                    hasil.getString("namaplg"),
                    hasil.getString("jenis"),
                    hasil.getString("telepon"),
                    hasil.getString("alamat")
                });
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
            "Data gagal dipanggil : "+ e.getMessage());
        }
    }
}